fix: remove occurences of the futurely deprecated title struct
ratatui/ratatui-website pull request #741
Opened 2024-10-04 10:28 UTC by TadoTheMiner

This issue fixes #740

2024-10-04 12:57 UTC, orhun approved these changes

2024-10-04 20:52 UTC, joshka requested changes
The examples should generally be copied verbatim from the ratatui repo, so that they stay in sync with what we're releasing. The process for this is a bit more complex than a standard PR approach and is documented in the examples folder [README](https://github.com/ratatui/ratatui-website/blob/main/code/examples/ratatui-examples/README.md). So for now, remove these files from this PR and I'll do the fixup based on the syncing the examples instead.

Other than that, I've added some nit suggestions to simplify the code a touch more.

2024-10-04 20:52 UTC, joshka commented on code/templates/async-template-counter/src/components/fps.rs
> +    let block = Block::default().title(Line::from(s.dim()).alignment(Alignment::Right));
```suggestion
    let block = Block::default().title(Line::from(s).dim().right_aligned());
```

2024-10-04 20:52 UTC, joshka commented on code/tutorials/counter-app-basic/src/main.rs
> +            .title_bottom(instructions.alignment(Alignment::Center))
```suggestion
            .title_bottom(instructions.centered())
```

2024-10-04 20:52 UTC, joshka commented on code/tutorials/counter-app-error-handling/src/main.rs
> +            .title_bottom(instructions.alignment(Alignment::Center))
```suggestion
            .title_bottom(instructions.centered())
```

2024-10-04 20:52 UTC, joshka commented on src/content/docs/recipes/widgets/block.md
> +    .title(Line::from("Right Title").alignment(Alignment::Right))
```suggestion
    .title(Line::from("Left Title").left_aligned())
    .title(Line::from("Middle Title").centered())
    .title(Line::from("Right Title").right_aligned())
```

2024-11-07 11:02 UTC, TadoTheMiner commented
Are you aware of my changes?

2024-11-07 11:58 UTC, joshka commented
> Are you aware of my changes?

The first comment in the review is the part that matters here the most "The examples should generally be copied verbatim from the ratatui repo,"

I may have been a bit unclear about what exactly I meant by this though, so my apologies. We don't edit the example code in this repo. It is authored in the ratatui repo and then copied into this repo sometime after each release so that the website code aligns with the latest release (although sometimes there can be some post-release updates). The process for doing that is a bit complex as I prefer to graft the history from the other repo into this one rather than having them disconnected. This is documented in the [examples README](https://github.com/ratatui/ratatui-website/blob/main/code/examples/ratatui-examples/README.md). Because of this complexity it's usually something I do as it can be fragile to moves / deletions / refactoring etc. (so the instructions are likely not 100% correct).

2024-11-07 12:53 UTC, TadoTheMiner commented
I've meant that I deleted the examples and accepted your changes

2024-11-07 13:01 UTC, joshka approved these changes

2024-11-07 13:02 UTC, joshka commented
> I've meant that I deleted the examples and accepted your changes

Ah got it - I just re-read the PR changes. Apologies. I missed that the examples were no longer a part of this.

2024-11-07 13:03 UTC, merged